/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:c7f05139-425c-4368-9776-e168a16c446b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_xcCwQq2jg",
    "aws_user_pools_web_client_id": "6it7nfhjcacuh3mm31298i584v",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "projectpipi-profilepics-267689146636336db-main",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
